# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Medimo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Charts'
    pod 'Bolts-Swift'
    pod 'Parse'

  target 'MedimoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MedimoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
